module.exports = {
    BilaraData: require("./src/bilara-data"),
    BilaraPath: require("./src/bilara-path"),
    BilaraPathMap: require("./src/bilara-path-map"),
    DETranslation: require("./src/de-translation"),
    English: require("./src/english"),
    ExecGit: require("./src/exec-git"),
    ExecGitMock: require("./src/exec-git-mock"),
    FuzzyWordSet: require("./src/fuzzy-word-set"),
    MLDoc: require("./src/ml-doc"),
    Pali: require("./src/pali"),
    Publication: require("./src/publication"),
    Seeker: require("./src/seeker"),
    SegDoc: require("./src/seg-doc"),
    SuidMap: require("./src/auto/suidmap"),
    SuttaCentralId: require("./src/sutta-central-id"),
    Tipitaka: require('./src/tipitaka'),
    Unicode: require("./src/unicode.js"),
    Verse: require("./src/verse.js"),

"" : ""};
