#!/bin/bash
DIR=`dirname $0`
EDITOR=$1
if [ "$EDITOR" == "" ]; then
    cat <<HELP
NAME
        bilara-edit - edit results of previous search

SYNOPSIS
        bilara-edit vi
        bilara-edit vim
        bilara-edit subl

DESCRIPTION
        Opens specified editor (vi, vim, subl) on files matching
        last search pattern.

HELP
exit 0
fi

if [ "$EDITOR" == "vim" ]; then
    SUFFIX=vi
else
    SUFFIX=$EDITOR
fi
bash -c "$EDITOR `cat $DIR/../local/bls_edit.${SUFFIX}`" 
