#!/bin/bash
DIR=`dirname $0`
pushd $DIR/..

# DEBUG
MSG="TEST_TOKEN $TEST_TOKEN"
echo "hello $MSG"
if [ "$TEST_TOKEN" == "test-token" ]; then
  echo ok
else
  echo sadness
fi
 
exit 0

$DIR/js/build.js

git status | grep 'nothing to commit' > /dev/null; RC=$?
if [ "$RC" == "0" ]; then
    echo -e "BUILD\t: Nothing to commit"
else
    echo -e "BUILD\t: committing..."
    git commit -am "build"
    npm version patch
    VERSION=`$DIR/version`
    git reset --soft HEAD~1
    git commit --amend -m "v$VERSION build"
    git push
    npm publish
fi
