#!/bin/bash
DIR=`dirname $0`

$DIR/js/build.js
VERSION=`json version < $DIR/../package.json`

git status | grep 'nothing to commit' > /dev/null; RC=$?
if [ "$RC" == "0" ]; then
    echo -e "BUILD\t: Nothing to commit"
else
    echo -e "BUILD\t: committing..."
    git commit -am "v$VERSION build"
    npm version patch
fi
