#!/bin/bash
DIR=`dirname $0`
pushd $DIR/..

js/build.js


git status | grep 'nothing to commit' > /dev/null; RC=$?
if [ "$RC" == "0" ]; then
    echo -e "BUILD\t: Nothing to commit"
else
    echo -e "BUILD\t: committing..."
    git commit -am "build"
    npm version patch
    VERSION=`json version < package.json`
    git commit --amend -m "v$VERSION build"
fi
