#!/bin/bash
DIR=`dirname $0`
DIR=`readlink -f $DIR`
pushd $DIR/../local/bilara-data >& /dev/null

SUID=$1
if [ "$SUID" == "" ]; then
    cat <<HELP
NAME
        de-branch - work on a de/sabbamitta sutta

DESCRIPTION
    de-branch SUID
        Switch to the de_sabbamitta_SUID branch of bilara-data.
        If the branch does not exist, create it and copy
        de/sabbamitta/.../SUID_translation-de-sabbamitta.json
        from en/sujato/.../SUID_translation-en-sujato.json

EXAMPLES
    de-branch an3.1
HELP
    exit 0
fi

$DIR/js/branch.js $SUID de sabbamitta 

