#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

${DIR}/install-node 24 &&
${DIR}/update-npm 11 &&
${DIR}/install-ripgrep &&
npm install && 
echo -e "${SCRIPT}: completed (OK)"
