#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
mkdir -p $DIR/local; pushd $DIR/local > /dev/null

RQDVER=$1
if [ "${RQDVER}" == "" ]; then
  RQDVER=12.1.1
fi
VER=`rg --version | head -1 | sed -e 's/[^ ]* \([0-9.]*\).*/\1/'`
if [ "$VER" == "${RQDVER}" ]; then
  echo "$SCRIPT:" Expected:${RQDVER} Actual:$VER "(OK)"
else
  echo "$SCRIPT: installing ripgrep ${RQDVER}"
  curl -LO https://github.com/BurntSushi/ripgrep/releases/download/${RQDVER}/ripgrep_${RQDVER}_amd64.deb
  sudo dpkg -i ripgrep_${RQDVER}_amd64.deb
fi
