#!/bin/bash
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

RQDVER=17
NODEVER=`/usr/bin/node --version | sed -e 's/\..*//'`
if [ "$NODEVER" == "v${RQDVER}" ]; then
    echo -e "${SCRIPT}: node ${NODEVER} found (OK)"
    exit 0
fi
if [ ! -x /usr/bin/curl ]; then
    echo -e "${SCRIPT}: apt-get install curl"
    sudo apt-get install -y curl
fi
if [ -e /usr/bin/node ]; then
    echo -e "${SCRIPT}: apt-get remove nodejs@${NODEVER} "
    sudo apt-get remove -y nodejs
    echo -e "${SCRIPT}: apt autoremove ... "
    sudo apt autoremove -y
fi
echo -e "${SCRIPT}: apt-get install nodejs@${RQDVER} "
curl -fsSL https://deb.nodesource.com/setup_${RQDVER}.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo ln -s /usr/bin/node /usr/sbin/node

