#!/bin/bash
DIR=`dirname $0`
${DIR}/install-node14
npm install
mkdir -p local
cd local
if [ -e bilara-data ]; then
    echo -e "INSTALL\t: bilara-data (OK)"
else
    echo -e "INSTALL\t: installing bilara-data"
    git clone https://github.com/suttacentral/bilara-data
fi

MSG=`type rg`
RC=$?; if [ "$RC" == "0" ]; then
    echo -e "INSTALL\t: $MSG (OK)"
else
    echo -e "INSTALL\t: installing ripgrep 12.1.1"
    curl -LO https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb
    sudo dpkg -i ripgrep_12.1.1_amd64.deb
fi
