#!/bin/bash
DIR=`dirname $0`
pushd $DIR/..
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

PUBVER=`npm view | grep latest | sed s/^.*:.//`
PKGVER=`grep version package.json | head -1 | sed s/[^0-9.]//g`
if [ "$PUBVER" == "PKGVER" ]; then
  echo "$SCRIPT: $PKGVER no change"
  echo -1
elif [ "$NODE_AUTH_TOKEN" != "" ]; then
  echo "$SCRIPT: $PUBVER updated to $PKGVER "
  npm publish
  exit 0
else 
    echo "$SCRIPT: cannot publish v$PKGVER (NODE_AUTH_TOKEN?)"
fi
