#!/bin/bash
DIR=`dirname $0`
BRANCH=$1
echo -e "BILARA\t: $0 DIR:$DIR"
if [ "$BRANCH" == "" ]; then BRANCH=unpublished; fi
cd ${DIR}/../local/bilara-data > /dev/null
echo -e "BILARA\t: BRANCH:$BRANCH pwd:"`pwd`

git remote -v | grep "upstream" > /dev/null
RC=$?
if [ "$RC" == "0" ]; then
  echo -e "BILARA\t: upstream remote found (OK)"
elif git remote -v | grep suttacentral > /dev/null; then
  echo -e "BILARA\t: suttacentral remote found (OK)"
else
  echo -e "BILARA\t: adding suttacentral remote"
  git remote add suttacentral https://github.com/suttacentral/bilara-data.git
fi
git fetch suttacentral
git fetch
if git checkout $BRANCH >& /dev/null; then
  echo -e "BILARA\t: on $BRANCH branch" 
else
  echo -e "BILARA\t: fetching $BRANCH branch" 
  git track --track origin/$BRANCH $BRANCH
fi

echo -e "BILARA\t: Refreshing $BRANCH fork from Github..." && \
git pull --rebase 

echo -e "BILARA\t: Refreshing $BRANCH fork from suttacentral ..." && \
git pull -Xtheirs --no-edit https://github.com/suttacentral/bilara-data 

echo -e "BILARA\t: Committing $BRANCH changes to bilara-data..." && \
git commit -am "SuttaCentral Update" 

echo -e "BILARA\t: Pushing changes to Github..." && \
git push
