#!/bin/bash
DIR=`dirname $0`; 
pushd $DIR/..
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

echo "npm version:" `npm -v`
npm install --verbose --save scv-esm@latest
npm install --verbose --save suttacentral-api@latest
npm install --verbose --save log-instance@latest
npm install --verbose --save memo-again@latest
npm install --verbose --save merkle-json@latest
$DIR/js/suidmap.js
$DIR/examples PUSH
