#!/bin/bash
DIR=`dirname $0`
echo $DIR
DOCS=
ARGS=

while (( "$#" )); do
  case "$1" in
    -*|--*=) # unsupported flags
      if [ "$ARGS" == "" ]; then
        ARGS=$1
      else
          ARGS="$ARGS $1"
      fi
      shift
      ;;
    *) # preserve positional arguments
      if [ "$DOCS" == "" ]; then
          DOCS=$1
      else
          DOCS="$DOCS $1"
      fi
      shift
      ;;
  esac
done
echo "ARGS=[$ARGS]"
echo "DOCS=[$DOCS]"

if [ "$DOCS" == "" ]; then DOCS='all'; fi

if [ "$DOCS" == "all" ] || [ "$DOCS" == "an" ]; then
    $DIR/js/verify.js $ARGS an1.1-9999
    $DIR/js/verify.js $ARGS an2.1-9999
    $DIR/js/verify.js $ARGS an3.1-9999
    $DIR/js/verify.js $ARGS an4.1-9999
    $DIR/js/verify.js $ARGS an5.1-9999
    $DIR/js/verify.js $ARGS an6.1-9999
    $DIR/js/verify.js $ARGS an7.1-9999
    $DIR/js/verify.js $ARGS an8.1-9999
    $DIR/js/verify.js $ARGS an9.1-9999
    $DIR/js/verify.js $ARGS an10.1-9999
    $DIR/js/verify.js $ARGS an11.1-9999
    if [ "$DOCS" != "all" ]; then DOCS=; fi
fi

if [ "$DOCS" == "all" ] || [ "$DOCS" == "sn" ]; then
    $DIR/js/verify.js $ARGS sn1.1-999
    $DIR/js/verify.js $ARGS sn2.1-999
    $DIR/js/verify.js $ARGS sn3.1-999
    $DIR/js/verify.js $ARGS sn4.1-999
    $DIR/js/verify.js $ARGS sn5.1-999
    $DIR/js/verify.js $ARGS sn6.1-999
    $DIR/js/verify.js $ARGS sn7.1-999
    $DIR/js/verify.js $ARGS sn8.1-999
    $DIR/js/verify.js $ARGS sn9.1-999
    $DIR/js/verify.js $ARGS sn10.1-999
    $DIR/js/verify.js $ARGS sn11.1-999
    $DIR/js/verify.js $ARGS sn12.1-999
    $DIR/js/verify.js $ARGS sn13.1-999
    $DIR/js/verify.js $ARGS sn14.1-999
    $DIR/js/verify.js $ARGS sn15.1-999
    $DIR/js/verify.js $ARGS sn16.1-999
    $DIR/js/verify.js $ARGS sn17.1-999
    $DIR/js/verify.js $ARGS sn18.1-999
    $DIR/js/verify.js $ARGS sn19.1-999
    $DIR/js/verify.js $ARGS sn20.1-999
    if [ "$DOCS" != "all" ]; then DOCS=; fi
fi

if [ "$DOCS" == "all" ] || [ "$DOCS" == "mn" ]; then
    $DIR/js/verify.js $ARGS mn1-999
    if [ "$DOCS" != "all" ]; then DOCS=; fi
fi

if [ "$DOCS" == "all" ] || [ "$DOCS" == "dn" ]; then
    $DIR/js/verify.js $ARGS dn1-999
    if [ "$DOCS" != "all" ]; then DOCS=; fi
fi

if [ "$DOCS" == "all" ] || [ "$DOCS" == "thig" ]; then
    $DIR/js/verify.js $ARGS thig1.1-999
    $DIR/js/verify.js $ARGS thig2.1-999
    $DIR/js/verify.js $ARGS thig3.1-999
    $DIR/js/verify.js $ARGS thig4.1-999
    $DIR/js/verify.js $ARGS thig5.1-999
    $DIR/js/verify.js $ARGS thig6.1-999
    $DIR/js/verify.js $ARGS thig7.1-999
    $DIR/js/verify.js $ARGS thig8.1-999
    $DIR/js/verify.js $ARGS thig9.1-999
    $DIR/js/verify.js $ARGS thig10.1-999
    $DIR/js/verify.js $ARGS thig11.1-999
    $DIR/js/verify.js $ARGS thig12.1-999
    $DIR/js/verify.js $ARGS thig13.1-999
    $DIR/js/verify.js $ARGS thig14.1-999
    $DIR/js/verify.js $ARGS thig15.1-999
    $DIR/js/verify.js $ARGS thig16.1-999
    if [ "$DOCS" != "all" ]; then DOCS=; fi
fi

if [ "$DOCS" == "all" ] || [ "$DOCS" == "thag" ]; then
    $DIR/js/verify.js $ARGS thag1.1-999
    $DIR/js/verify.js $ARGS thag2.1-999
    $DIR/js/verify.js $ARGS thag3.1-999
    $DIR/js/verify.js $ARGS thag4.1-999
    $DIR/js/verify.js $ARGS thag5.1-999
    $DIR/js/verify.js $ARGS thag6.1-999
    $DIR/js/verify.js $ARGS thag7.1-999
    $DIR/js/verify.js $ARGS thag8.1-999
    $DIR/js/verify.js $ARGS thag9.1-999
    $DIR/js/verify.js $ARGS thag10.1-999
    $DIR/js/verify.js $ARGS thag11.1-999
    $DIR/js/verify.js $ARGS thag12.1-999
    $DIR/js/verify.js $ARGS thag13.1-999
    $DIR/js/verify.js $ARGS thag14.1-999
    $DIR/js/verify.js $ARGS thag15.1-999
    $DIR/js/verify.js $ARGS thag16.1-999
    $DIR/js/verify.js $ARGS thag17.1-999
    $DIR/js/verify.js $ARGS thag18.1-999
    $DIR/js/verify.js $ARGS thag19.1-999
    $DIR/js/verify.js $ARGS thag20.1-999
    $DIR/js/verify.js $ARGS thag21.1-999
    if [ "$DOCS" != "all" ]; then DOCS=; fi
fi

if [ "$DOCS" == "all" ] || [ "$DOCS" == "bi" ]; then
    $DIR/js/verify.js $ARGS pli-tv-bi-vb-as1-999
    $DIR/js/verify.js $ARGS pli-tv-bi-vb-ss1-999
    $DIR/js/verify.js $ARGS pli-tv-bi-vb-np1-999
    $DIR/js/verify.js $ARGS pli-tv-bi-vb-pc1-999
    $DIR/js/verify.js $ARGS pli-tv-bi-vb-sk1-999
    $DIR/js/verify.js $ARGS pli-tv-bi-vb-pd1-999
    $DIR/js/verify.js $ARGS pli-tv-bi-vb-pj5-8
    if [ "$DOCS" != "all" ]; then DOCS=; fi
fi

if [ "$DOCS" == "all" ] || [ "$DOCS" == "kd" ]; then
    $DIR/js/verify.js $ARGS pli-tv-kd1-999
    if [ "$DOCS" != "all" ]; then DOCS=; fi
fi

if [ "$DOCS" == "all" ] || [ "$DOCS" == "bu" ]; then
    $DIR/js/verify.js $ARGS pli-tv-bu-vb-as1-999
    $DIR/js/verify.js $ARGS pli-tv-bu-vb-sk1-999
    $DIR/js/verify.js $ARGS pli-tv-bu-vb-pj1-999
    $DIR/js/verify.js $ARGS pli-tv-bu-vb-pd1-999
    $DIR/js/verify.js $ARGS pli-tv-bu-vb-ss1-999
    $DIR/js/verify.js $ARGS pli-tv-bu-vb-ay1-999
    $DIR/js/verify.js $ARGS pli-tv-bu-vb-np1-999
    $DIR/js/verify.js $ARGS pli-tv-bu-vb-pc1-999
    $DIR/js/verify.js $ARGS pli-tv-bu-vb-pj1-4
    if [ "$DOCS" != "all" ]; then DOCS=; fi
fi

if [ "$DOCS" == "all" ] || [ "$DOCS" == "pvr" ]; then
    $DIR/js/verify.js $ARGS pli-tv-pvr1.1-999
    $DIR/js/verify.js $ARGS pli-tv-pvr2.1-999
    $DIR/js/verify.js $ARGS pli-tv-pvr3-999
    if [ "$DOCS" != "all" ]; then DOCS=; fi
fi

if [ "$DOCS" != "all" ] && [ "$DOCS" != "" ]; then
    $DIR/js/verify.js $ARGS $DOCS
fi
